### ISSUE TITLE
Unittest compilation failed

### ISSUE THREAD

**Issue by jermainewang** [minerva-developers/minerva#11]
When compiling unittest, I got error on my machine (GCC 4.9.2 prerelease, Arch Linux 2015.03.01, kernel 3.18.6). This is caused by following things in this commit 2e886a4d6a8e04c803dbb117ecd048bb8fe867f8:
1. `unittest_main` is built as a shared library while for `gtest`, usually it only builds `.a`.
2. The `-flto` flag is not working with my GCC.

I suggest fixing them by changing back to static library for unittest and removing `lto` flag (or perform a corresponding check on that flag).

**Comment by jermainewang** [comment]
Follow ups:
After building the `libgtest.so`, the compiling is OK now. This indeed is not a bug, but for users that do not rely on the `resolve_deps.sh` script, I would say this is not convenient.

**Comment by hotpxl** [comment]
Would building `unittestn_main` as a shared library solve this problem?

**Comment by jermainewang** [comment]
The current setup is to build `unittest_main` as a shared library. So when linking to `gtest`, it also needs a shared object. Therefore, when building `gtest`, I need to pass `-DBUILD_SHARED_LIB` to the script. Anyhow, I am not clear with the benefits of static linking and dynamic linking so I am fine with current setting.

**Comment by hotpxl** [comment]
Let's change that back to static linking. My bad!
