### ISSUE TITLE
doesn't compile with cuDNN R2

### ISSUE THREAD

**Issue by hjk41** [minerva-developers/minerva#4]
cuDNN R2 has different interface than R1. Our code does not compile with R2, giving out messages like "identifier "cudnnTensor4dDescriptor_t" is undefined". We should fix it or at least give a warning about this.

**Comment by hotpxl** [comment]
I see

**Comment by jermainewang** [comment]
Shall we directly switch to R2? Or make a compatible version?

**Comment by hjk41** [comment]
Let's keep it for now until Yutian has free cycles. Currently we should
focus on performance diff first.

On Tue, Jan 6, 2015 at 10:55 PM, Minjie Wang <notifications@github.com>
wrote:

> Shall we directly switch to R2? Or make a compatible version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/4#issuecomment-68874834>
> .
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hotpxl** [comment]
See soumith/cudnn.torch#12 and torch/cutorch#87. Looks like R2 has some serious bugs and people is rolling back to R1. I suggest we wait for the final release.
