### ISSUE TITLE
Is it easy(possible) to implement RNN?

### ISSUE THREAD

**Issue by byzhang** [minerva-developers/minerva#8]
Could you provide a simple example?

**Comment by hotpxl** [comment]
I think we already have a running example of RNN.
@SerailHydra @sneakerkg 
Could you guys provide a frontend file?

**Comment by byzhang** [comment]
a kind ping...

**Comment by hotpxl** [comment]
sorry.. let me ping @SerailHydra again.

We have a simple LSTM/RNN example with fake data, would that suffice?

**Comment by byzhang** [comment]
Yes, it sounds helpful!

**Comment by SerailHydra** [comment]
Sorry for my late reply. Have been busy for several days. I will send you
code later. Is it simple RNN example you want? For now we only have LSTM at
hand.

2015-03-10 2:37 GMT-04:00 byzhang <notifications@github.com>:

> Yes, it sounds helpful!
> On Mar 9, 2015 11:36 PM, "Hot.PxL" <notifications@github.com> wrote:
>
> > sorry.. let me ping @SerailHydra <https://github.com/SerailHydra> again.
> >
> > We have a simple LSTM/RNN example with fake data, would that suffice?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/minerva-developers/minerva/issues/8#issuecomment-78002978
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/8#issuecomment-78003052>
> .
>



-- 
Hongyu Zhu
Embedded and Pervasive Computing Center (EPCC Lab)
ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China

**Comment by SerailHydra** [comment]
FYI, here is our current code and data for LSTM architecture. Put them in
minerva/owl/apps and do the following: The code is not perfect but it is
sufficient to show how to implement one with Minerva.

@minerva/:
1, cd release/owl
2, make
3, cd ../../owl/apps
4, ln -s ../../release/owl/libowl.sp
5, ln -s ../owl/
6, python lstm-example.py

Thanks

2015-03-10 9:38 GMT-04:00 Hongyu Zhu <serailhydra@gmail.com>:

> Sorry for my late reply. Have been busy for several days. I will send you
> code later. Is it simple RNN example you want? For now we only have LSTM at
> hand.
>
> 2015-03-10 2:37 GMT-04:00 byzhang <notifications@github.com>:
>
> Yes, it sounds helpful!
>> On Mar 9, 2015 11:36 PM, "Hot.PxL" <notifications@github.com> wrote:
>>
>> > sorry.. let me ping @SerailHydra <https://github.com/SerailHydra>
>> again.
>> >
>> > We have a simple LSTM/RNN example with fake data, would that suffice?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/minerva-developers/minerva/issues/8#issuecomment-78002978
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/minerva-developers/minerva/issues/8#issuecomment-78003052>
>> .
>>
>
>
>
> --
> Hongyu Zhu
> Embedded and Pervasive Computing Center (EPCC Lab)
> ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China
>



-- 
Hongyu Zhu
Embedded and Pervasive Computing Center (EPCC Lab)
ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China

**Comment by byzhang** [comment]
@SerailHydra , did you try to share the code and data as attachment? They are probably filtered by github. Can you checkin them?

**Comment by SerailHydra** [comment]
give me your email and I will send them to you directly

2015-03-10 18:23 GMT-04:00 byzhang <notifications@github.com>:

> @SerailHydra <https://github.com/SerailHydra> , did you try to share the
> code and data as attachment? They are probably filtered by github. Can you
> checkin them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/8#issuecomment-78161709>
> .
>



-- 
Hongyu Zhu
Embedded and Pervasive Computing Center (EPCC Lab)
ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China

**Comment by byzhang** [comment]
Thanks

**Comment by gujunli** [comment]
Hi :

Will the LSTM code be public? I am interested in taking a look.

This is Junli Gu from AMD research, Beijing lab.

Thanks!
junli

On Wed, Mar 11, 2015 at 7:51 AM, SerailHydra <notifications@github.com>
wrote:

> give me your email and I will send them to you directly
>
> 2015-03-10 18:23 GMT-04:00 byzhang <notifications@github.com>:
>
> > @SerailHydra <https://github.com/SerailHydra> , did you try to share the
> > code and data as attachment? They are probably filtered by github. Can
> you
> > checkin them?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/minerva-developers/minerva/issues/8#issuecomment-78161709
> >
> > .
> >
>
>
>
> --
> Hongyu Zhu
> Embedded and Pervasive Computing Center (EPCC Lab)
> ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/8#issuecomment-78173927>
> .
>



-- 
************************************************
Junli Gu--谷俊丽
Coordinated Science Lab
University of Illinois at Urbana-Champaign
************************************************

**Comment by SerailHydra** [comment]
Yes. We have an initiative version now, and we are still working on
improving it.

2015-03-11 3:06 GMT-04:00 gujunli <notifications@github.com>:

> Hi :
>
> Will the LSTM code be public? I am interested in taking a look.
>
> This is Junli Gu from AMD research, Beijing lab.
>
> Thanks!
> junli
>
> On Wed, Mar 11, 2015 at 7:51 AM, SerailHydra <notifications@github.com>
> wrote:
>
> > give me your email and I will send them to you directly
> >
> > 2015-03-10 18:23 GMT-04:00 byzhang <notifications@github.com>:
> >
> > > @SerailHydra <https://github.com/SerailHydra> , did you try to share
> the
> > > code and data as attachment? They are probably filtered by github. Can
> > you
> > > checkin them?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/minerva-developers/minerva/issues/8#issuecomment-78161709
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Hongyu Zhu
> > Embedded and Pervasive Computing Center (EPCC Lab)
> > ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/minerva-developers/minerva/issues/8#issuecomment-78173927
> >
> > .
> >
>
>
>
> --
> ************************************************
> Junli Gu--谷俊丽
> Coordinated Science Lab
> University of Illinois at Urbana-Champaign
> ************************************************
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/8#issuecomment-78214766>
> .
>



-- 
Hongyu Zhu
Embedded and Pervasive Computing Center (EPCC Lab)
ACM class, Shanghai Jiao Tong University, Shanghai, 200240, China
