### ISSUE TITLE
mnist_cnn failed at Epoch #0

### ISSUE THREAD

**Issue by byzhang** [minerva-developers/minerva#9]
Here is the error:
F0310 16:38:25.787619  9513 narray.cpp:126] Check failed: lhs.Size(1) == rhs.Size(0) (512 vs. -6833920) size must match
the acts[6] has size: [32845682 4 32 256 ], and minibatch_size is 256.

**Comment by hjk41** [comment]
Could you share the full error message? It seems you have a bad Narray
(with dimension -6833920). Probably that's caused by bad data file.

On Wed, Mar 11, 2015 at 7:40 AM, byzhang <notifications@github.com> wrote:

> Here is the error:
> F0310 16:38:25.787619 9513 narray.cpp:126] Check failed: lhs.Size(1) ==
> rhs.Size(0) (512 vs. -6833920) size must match
> the acts[6] has size: [32845682 4 32 256 ], and minibatch_size is 256.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/9>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by byzhang** [comment]
Ah, I forgot to mention the core dump is from minerva/apps/mnist_cnn.cpp:107.
And I add a log to print the size of acts[6]. Is it overflowed?
I used the training data from baidu pan.

**Comment by jermainewang** [comment]
We have fixed that problem in the latest push. Basically, we are working on
the python interface for a long time so we haven't tested the c++ program
for a while. We will keep an eye on these applications. Sorry about this.

BTW, you could also try our python interface. It is easier to debug to some
extent.

On Wed, Mar 11, 2015 at 12:00 AM, byzhang <notifications@github.com> wrote:

> Ah, I forgot to mention the core dump is from
> minerva/apps/mnist_cnn.cpp:107.
> And I add a log to print the size of acts[6]. Is it overflowed?
> I used the training data from baidu pan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/9#issuecomment-78201533>
> .
>



-- 
Minjie Wang
*New York University | Computer Science*
715 Broadway, New York, NY, 10009

**Comment by byzhang** [comment]
It seems unit tests also break, e.g.:
```
minerva/tests/unittest_conv_forward.cpp: In member function ‘virtual void ConvForward_GpuWithoutPadding_Test::TestBody()’:
minerva/tests/unittest_conv_forward.cpp:27:32: error: no matching function for call to ‘minerva::ConvInfo::ConvInfo(<brace-enclosed initializer list>)’
   ConvInfo conv_info{0, 0, 1, 1};
                                ^
minerva/tests/unittest_conv_forward.cpp:27:32: note: candidates are:
In file included from minerva/minerva/op/closure.h:4:0,
                 from minerva/minerva/narray/narray.h:3,
                 from minerva/minerva/minerva.h:4,
                 from minerva/tests/unittest_main.h:2,
                 from minerva/tests/unittest_conv_forward.cpp:1:
minerva/minerva/narray/convolution_info.h:6:3: note: minerva::ConvInfo::ConvInfo()
   ConvInfo(): pad_height(0), pad_width(0),
   ^
minerva/minerva/narray/convolution_info.h:6:3: note:   candidate expects 0 arguments, 4 provided
minerva/minerva/narray/convolution_info.h:5:8: note: constexpr minerva::ConvInfo::ConvInfo(const minerva::ConvInfo&)
 struct ConvInfo {
        ^
minerva/minerva/narray/convolution_info.h:5:8: note:   candidate expects 1 argument, 4 provided
minerva/minerva/narray/convolution_info.h:5:8: note: constexpr minerva::ConvInfo::ConvInfo(minerva::ConvInfo&&)
minerva/minerva/narray/convolution_info.h:5:8: note:   candidate expects 1 argument, 4 provided

**Comment by jermainewang** [comment]
Fixed.

On Wed, Mar 11, 2015 at 2:51 AM, byzhang <notifications@github.com> wrote:

> It seems unit tests also break, e.g.:
>
> minerva/tests/unittest_conv_forward.cpp: In member function ‘virtual void ConvForward_GpuWithoutPadding_Test::TestBody()’:
> minerva/tests/unittest_conv_forward.cpp:27:32: error: no matching function for call to ‘minerva::ConvInfo::ConvInfo(<brace-enclosed initializer list>)’
>    ConvInfo conv_info{0, 0, 1, 1};
>                                 ^
> minerva/tests/unittest_conv_forward.cpp:27:32: note: candidates are:
> In file included from minerva/minerva/op/closure.h:4:0,
>                  from minerva/minerva/narray/narray.h:3,
>                  from minerva/minerva/minerva.h:4,
>                  from minerva/tests/unittest_main.h:2,
>                  from minerva/tests/unittest_conv_forward.cpp:1:
> minerva/minerva/narray/convolution_info.h:6:3: note: minerva::ConvInfo::ConvInfo()
>    ConvInfo(): pad_height(0), pad_width(0),
>    ^
> minerva/minerva/narray/convolution_info.h:6:3: note:   candidate expects 0 arguments, 4 provided
> minerva/minerva/narray/convolution_info.h:5:8: note: constexpr minerva::ConvInfo::ConvInfo(const minerva::ConvInfo&)
>  struct ConvInfo {
>         ^
> minerva/minerva/narray/convolution_info.h:5:8: note:   candidate expects 1 argument, 4 provided
> minerva/minerva/narray/convolution_info.h:5:8: note: constexpr minerva::ConvInfo::ConvInfo(minerva::ConvInfo&&)
> minerva/minerva/narray/convolution_info.h:5:8: note:   candidate expects 1 argument, 4 provided
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/9#issuecomment-78213646>
> .
>



-- 
Minjie Wang
*New York University | Computer Science*
715 Broadway, New York, NY, 10009
